#!/bin/sh
# Pack an installable package
# USAGE: build_release <version>
SOURCE_DIR=~/Code/yotsuba
STAGE_AREA=~/Code/yotsuba-release
PACKAGE_ID=yotsuba-$1.tar.gz
echo
echo "Staging a package for Yotsuba $1"
cd $SOURCE_DIR
mkdir -p $STAGE_AREA
cp -r $SOURCE_DIR/yotsuba $SOURCE_DIR/setup.py $STAGE_AREA
cd $STAGE_AREA
echo "Packing for Yotsuba $1"
tar czvf $PACKAGE_ID *
mv $PACKAGE_ID ../
cd ../
rm -Rf $STAGE_AREA
echo "Done"
echo
