#!/bin/sh
echo
echo "Creating Egg Package for Yotsuba"
rm *.egg
cp yotsuba.py egg-packer/yotsuba/__init__.py &&\
svn export egg-packer yotsuba &&\
tar -czf yotsuba-2.1-pkg.tar.gz yotsuba &&\
cd yotsuba &&\
python setup.py bdist_egg &&\
mv dist/*.egg ../ &&\
cd ../ &&\
rm -Rf yotsuba &&\
echo "Python Egg Package for Yotsuba created" &&\
echo
